services:
  - type: web
    name: quiz
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: QUESTIONS_PASSWORD
        value: Ppawel
